"""STaR outer loop for the Healthcare AI GYM rebuttal.

REIMPLEMENTATION NOTICE
=======================
Independent reimplementation of STaR (Zelikman, Wu, Mu & Goodman, NeurIPS
2022, arXiv:2203.14465).  ``github.com/ezelikman/STaR`` was NOT run — it is
JAX 0.2.12 / mesh-transformer-jax / GPT-J-6B on TPU + Ray and does not run on
this cluster.  Deviations are enumerated in ``baselines/STAR_PORT.md``.

THE LOOP
========
STaR Algorithm 1, with the paper's two structural choices kept:

    M_0 <- base
    for n in 1..N:
        rollouts <- M_{n-1} over the training pool          (star_generate.py)
        D_n      <- rollouts that passed the acceptance test
        M_n      <- fine_tune(BASE, D_n)                     (sft_trainer.py)

Two details that are easy to get wrong and that the paper is explicit about:

  * ``--init-from base`` (default).  Every iteration fine-tunes the ORIGINAL
    backbone, not the previous iteration's checkpoint.  Zelikman et al. train
    from the original pretrained model each outer loop "to avoid overfitting".
    ``--init-from previous`` gives the continual-training variant.
  * ``--dataset-scope current`` (default).  D_n is the CURRENT iteration's
    accepted set; it is not accumulated across iterations, because the
    rationales are re-generated by the improved policy each time.
    ``--dataset-scope accumulated`` gives the union variant.

Everything the rebuttal needs to plot the curve rather than a single endpoint
is persisted per iteration: acceptance rate, task coverage, dataset size, the
full score distribution, and a held-out score measured with the same GYM loop
every other condition in the paper is measured with.

Usage
-----
    python scripts/rebuttal/star_iterate.py \
        --base-model /path/to/Qwen3.5-9B \
        --out-root   /path/to/hcgym_rebuttal/baselines/STaR/q9b_star \
        --iterations 3 --samples-per-task 3 --max-turns 5 \
        --accept-on qa_accuracy

    python scripts/rebuttal/star_iterate.py ... --dry-run   # print the plan, run nothing
"""

from __future__ import annotations

import argparse
import json
import os
import shlex
import signal
import subprocess
import sys
import time
import urllib.request
from dataclasses import asdict, dataclass
from datetime import datetime
from pathlib import Path
from typing import Optional

HCGYM_ROOT = Path(__file__).resolve().parents[2]
if str(HCGYM_ROOT) not in sys.path:
    sys.path.insert(0, str(HCGYM_ROOT))

from loguru import logger  # noqa: E402

STAR_GENERATE = HCGYM_ROOT / "scripts" / "rebuttal" / "star_generate.py"
SFT_TRAINER = HCGYM_ROOT / "bioagents" / "training" / "sft_trainer.py"


# ══════════════════════════════════════════════════════════════════════
#  Config
# ══════════════════════════════════════════════════════════════════════


@dataclass
class LoopConfig:
    base_model: str = ""
    out_root: str = ""
    iterations: int = 3

    # Generation (mirrors star_generate.GenConfig; kept flat for the CLI)
    pool: str = "full_4modality_clean"
    split: str = "train"
    limit: int = 0
    samples_per_task: int = 3
    temperature: float = 1.0
    max_turns: int = 5
    max_new_tokens: int = 2048
    workers: int = 8
    no_think: bool = True
    seed: int = 42

    # Acceptance
    accept_on: str = "qa_accuracy"
    accept_threshold: Optional[float] = None
    max_accepted_per_task: int = 1
    allow_uninformative: bool = False

    # STaR structure
    init_from: str = "base"           # base | previous
    dataset_scope: str = "current"    # current | accumulated
    sft_source: str = "sft_path"      # sft_path | trajectory_dir

    # SFT
    sft_gpus: int = 7                 # same student topology as the RL arms
    sft_epochs: int = 2
    sft_lr: float = 1e-5
    sft_batch: int = 1
    sft_grad_accum: int = 8
    sft_max_length: int = 8192
    sft_max_samples: int = 200000     # must exceed |D_n| or the trainer silently subsamples
    peft: bool = False                # full-parameter, matching the RL arms
    peft_r: int = 16

    # Serving
    serve_port: int = 31500
    serve_gpus: int = 8
    serve_context: int = 32768
    serve_mem_fraction: float = 0.85
    server_url: Optional[str] = None  # external server; skips serve/stop

    # Held-out probe
    heldout_split: str = "test"
    heldout_size: int = 200
    heldout_temperature: float = 0.1

    dry_run: bool = False
    resume: bool = True


# ══════════════════════════════════════════════════════════════════════
#  Serving
# ══════════════════════════════════════════════════════════════════════


def _server_healthy(url: str, timeout: float = 5.0) -> bool:
    try:
        with urllib.request.urlopen(f"{url}/v1/models", timeout=timeout) as r:
            return r.status == 200
    except Exception:
        return False


class SglangServer:
    """Serve one checkpoint for the generation phase.

    Mirrors ``runs/eval_agentic.slurm``'s launch and liveness check, including
    ``--attention-backend triton``: verl hardcodes ``fa3`` elsewhere on this
    fleet and fa3 raises on Blackwell, so triton is the one that works here.
    """

    def __init__(self, model: str, port: int, gpus: int, log_path: Path,
                 context: int = 32768, mem_fraction: float = 0.85):
        self.model, self.port, self.gpus = model, port, gpus
        self.log_path, self.context, self.mem_fraction = log_path, context, mem_fraction
        self.proc: Optional[subprocess.Popen] = None

    @property
    def url(self) -> str:
        return f"http://127.0.0.1:{self.port}"

    def command(self) -> list[str]:
        return [
            sys.executable, "-m", "sglang.launch_server",
            "--model-path", self.model,
            "--served-model-name", "hcgym",
            "--host", "127.0.0.1", "--port", str(self.port),
            "--trust-remote-code",
            "--context-length", str(self.context),
            "--mem-fraction-static", str(self.mem_fraction),
            "--tp-size", "1",
            # Data parallel across the whole node: generation is the dominant
            # cost of a STaR iteration and star_generate drives the server with
            # --workers concurrent episodes.
            "--dp-size", str(self.gpus),
            "--attention-backend", "triton",
            # The standalone-server equivalent of the RL arms'
            # engine_kwargs.sglang.mm_attention_backend=triton_attn: verl
            # defaults that to "fa3", which raises on Blackwell for any VLM
            # backbone.  Harmless for a text-only backbone (sglang only reads it
            # on the vision path).  The RL arms' other B200 setting,
            # free_cache_engine=False, has no counterpart here: it exists
            # because verl colocates actor and rollout and releases sglang's KV
            # cache through TorchMemorySaver, whose resume writes in place to an
            # inference_mode tensor and dies.  This server is not owned by verl,
            # holds no colocated actor and is never released mid-run, so
            # TorchMemorySaver is not in the picture at all.
            "--mm-attention-backend", "triton_attn",
        ]

    def start(self, wait_s: int = 3000) -> str:
        self.log_path.parent.mkdir(parents=True, exist_ok=True)
        logger.info(f"[star] serving {self.model} on {self.url} ({self.gpus} GPU)")
        with self.log_path.open("w") as lf:
            self.proc = subprocess.Popen(self.command(), stdout=lf, stderr=subprocess.STDOUT,
                                         start_new_session=True)
        t0 = time.time()
        while time.time() - t0 < wait_s:
            if _server_healthy(self.url):
                logger.info(f"[star] server healthy after {time.time() - t0:.0f}s")
                return self.url
            if self.proc.poll() is not None:
                tail = self.log_path.read_text(errors="ignore")[-4000:]
                raise RuntimeError(f"sglang died during startup:\n{tail}")
            time.sleep(10)
        self.stop()
        raise TimeoutError(f"sglang never became healthy within {wait_s}s")

    def stop(self):
        if self.proc and self.proc.poll() is None:
            try:
                os.killpg(os.getpgid(self.proc.pid), signal.SIGTERM)
                self.proc.wait(timeout=120)
            except Exception:
                try:
                    os.killpg(os.getpgid(self.proc.pid), signal.SIGKILL)
                except Exception:
                    pass
        self.proc = None


# ══════════════════════════════════════════════════════════════════════
#  Commands
# ══════════════════════════════════════════════════════════════════════


def generate_command(cfg: LoopConfig, model: str, server_url: str, out_dir: Path,
                     *, split: str, samples: int, temperature: float,
                     eval_only: bool, limit: int) -> list[str]:
    cmd = [
        sys.executable, str(STAR_GENERATE),
        "--model", model,
        "--backend", "sglang",
        "--server-url", server_url,
        "--pool", cfg.pool,
        "--split", split,
        "--samples-per-task", str(samples),
        "--temperature", str(temperature),
        "--top-p", "0.95",
        "--max-new-tokens", str(cfg.max_new_tokens),
        "--max-turns", str(cfg.max_turns),
        "--workers", str(cfg.workers),
        "--seed", str(cfg.seed),
        "--accept-on", cfg.accept_on,
        "--max-accepted-per-task", str(cfg.max_accepted_per_task),
        "--iterations-planned", str(cfg.iterations),
        "--out-dir", str(out_dir),
    ]
    if cfg.accept_threshold is not None:
        cmd += ["--accept-threshold", str(cfg.accept_threshold)]
    if cfg.no_think:
        cmd += ["--no-think"]
    if limit:
        cmd += ["--limit", str(limit)]
    if eval_only:
        # A held-out probe never writes training data and must never stop the
        # loop on a "degenerate acceptance rate" — for the probe that number is
        # the measurement, not a misconfiguration.
        cmd += ["--eval-only", "--no-keep-rejected", "--allow-uninformative"]
    elif cfg.allow_uninformative:
        cmd += ["--allow-uninformative"]
    return cmd


def sft_config_dict(cfg: LoopConfig, init_model: str, data_path: Path,
                    output_dir: Path, run_name: str) -> dict:
    """The YAML ``BioAgentSFTConfig.from_yaml`` consumes.

    Three settings here are load-bearing for the baseline being genuine rather
    than a strawman, and each is argued in STAR_PORT.md:

      qa_tasks_path: ""   The trainer DEFAULTS to
                          data/domains/medical_qa/tasks.json, and
                          ``qa_tasks_to_sft`` synthesises gold-answer
                          demonstrations from it.  Leaving it at the default
                          would silently mix oracle answers into a baseline
                          whose whole point is that it only ever sees its own
                          successful rollouts.  It must be empty.
      peft.enabled: false The RL arms update all parameters.  A LoRA-only STaR
                          arm would lose on capacity, not on method.
      min_reward: 0.0     star_generate has already applied the acceptance
                          test; the trainer's own filter re-reads
                          max(final_reward, action_score), which is a DIFFERENT
                          quantity from the acceptance signal.  Set to 0.0 it
                          is a pass-through over an already-filtered directory.
                          (Only used by the trajectory_dir source.)
    """
    d = {
        "model": {
            "name_or_path": init_model,
            "torch_dtype": "bfloat16",
            # sdpa: this venv has no flash-attn wheel and common_env.sh already
            # pins TRANSFORMERS_ATTN_IMPLEMENTATION=sdpa for every arm.
            "attn_implementation": "sdpa",
        },
        "peft": {
            "enabled": bool(cfg.peft),
            "r": cfg.peft_r,
            "lora_alpha": 2 * cfg.peft_r,
            "lora_dropout": 0.05,
            "target_modules": ["q_proj", "k_proj", "v_proj", "o_proj",
                               "gate_proj", "up_proj", "down_proj"],
        },
        "dataset": {
            "qa_tasks_path": "",
            "instruction_path": "",
            "min_reward": 0.0,
            "max_samples": cfg.sft_max_samples,
            "max_length": cfg.sft_max_length,
            "train_ratio": 0.95,
        },
        "training": {
            "output_dir": str(output_dir),
            "num_train_epochs": cfg.sft_epochs,
            "per_device_train_batch_size": cfg.sft_batch,
            "gradient_accumulation_steps": cfg.sft_grad_accum,
            "learning_rate": cfg.sft_lr,
            "lr_scheduler_type": "cosine",
            "warmup_ratio": 0.1,
            "bf16": True,
            "logging_steps": 5,
            "save_steps": 500,
            "eval_steps": 200,
            "save_total_limit": 1,
            "seed": cfg.seed,
        },
        "logging": {
            "project": "hcgym-rebuttal",
            "run_name": run_name,
            "use_wandb": os.environ.get("WANDB_DISABLED", "") != "true",
        },
    }
    if cfg.sft_source == "trajectory_dir":
        d["dataset"]["trajectory_dir"] = str(data_path)
        d["dataset"]["sft_path"] = ""
    else:
        d["dataset"]["sft_path"] = str(data_path)
        d["dataset"]["trajectory_dir"] = ""
    return d


def sft_command(cfg: LoopConfig, config_path: Path) -> list[str]:
    return [
        "accelerate", "launch",
        "--num_processes", str(cfg.sft_gpus),
        "--mixed_precision", "bf16",
        str(SFT_TRAINER),
        "--config", str(config_path),
    ]


# ══════════════════════════════════════════════════════════════════════
#  Hooks (so the loop is testable with no GPU)
# ══════════════════════════════════════════════════════════════════════


class Hooks:
    """Side effects of one iteration, isolated so tests can replace them."""

    def __init__(self, dry_run: bool = False):
        self.dry_run = dry_run
        self.calls: list[dict] = []

    def _run(self, cmd: list[str], cwd: Path, tag: str):
        self.calls.append({"tag": tag, "cmd": cmd})
        line = " ".join(shlex.quote(c) for c in cmd)
        if self.dry_run:
            print(f"DRYRUN {tag}: {line}")
            return 0
        logger.info(f"[star] {tag}: {line}")
        return subprocess.call(cmd, cwd=str(cwd))

    def serve(self, cfg: LoopConfig, model: str, log_path: Path):
        if cfg.server_url:
            return None, cfg.server_url
        srv = SglangServer(model, cfg.serve_port, cfg.serve_gpus, log_path,
                           cfg.serve_context, cfg.serve_mem_fraction)
        if self.dry_run:
            self.calls.append({"tag": "serve", "cmd": srv.command()})
            print("DRYRUN serve: " + " ".join(shlex.quote(c) for c in srv.command()))
            return None, srv.url
        return srv, srv.start()

    def stop(self, srv):
        if srv is not None:
            srv.stop()

    def generate(self, cmd: list[str], out_dir: Path) -> dict:
        rc = self._run(cmd, HCGYM_ROOT, "generate")
        if self.dry_run:
            return {"acceptance_rate": None, "n_selected": None, "dry_run": True}
        stats_path = out_dir / "gen_stats.json"
        if rc not in (0,) and not stats_path.exists():
            raise RuntimeError(f"star_generate failed (rc={rc}) and wrote no stats")
        stats = json.loads(stats_path.read_text(encoding="utf-8"))
        stats["_returncode"] = rc
        return stats

    def sft(self, cmd: list[str], output_dir: Path) -> str:
        rc = self._run(cmd, HCGYM_ROOT, "sft")
        final = output_dir / "final"
        if self.dry_run:
            return str(final)
        if rc != 0:
            raise RuntimeError(f"SFT failed with rc={rc}")
        if not (final / "config.json").exists():
            raise RuntimeError(f"SFT produced no usable checkpoint at {final}")
        return str(final)


# ══════════════════════════════════════════════════════════════════════
#  Bookkeeping
# ══════════════════════════════════════════════════════════════════════


def concat_sft_files(paths: list[Path], dest: Path) -> int:
    """Concatenate accepted-rollout jsonl files.  Returns the example count."""
    dest.parent.mkdir(parents=True, exist_ok=True)
    n = 0
    with dest.open("w", encoding="utf-8") as out:
        for p in paths:
            if not p.exists():
                continue
            for line in p.read_text(encoding="utf-8").splitlines():
                if line.strip():
                    out.write(line + "\n")
                    n += 1
    return n


def curve_row(it: int, policy: str, gen_stats: dict, heldout: dict,
              n_train_examples: int, init_model: str) -> dict:
    """One row of the curve the rebuttal plots instead of a single endpoint."""
    return {
        "iteration": it,
        "policy_rolled_out": policy,
        "sft_init_from": init_model,
        "acceptance_rate": gen_stats.get("acceptance_rate"),
        "task_coverage": gen_stats.get("task_coverage"),
        "n_rollouts": gen_stats.get("n_rollouts"),
        "n_accepted": gen_stats.get("n_accepted"),
        "n_selected": gen_stats.get("n_selected"),
        "n_train_examples": n_train_examples,
        "threshold_verdict": gen_stats.get("threshold_verdict"),
        "acceptance_if_accepted_on": gen_stats.get("acceptance_if_accepted_on"),
        "heldout": heldout,
        "timestamp": datetime.now().isoformat(),
    }


def heldout_summary(stats: dict) -> dict:
    """The held-out numbers worth carrying into the rebuttal table."""
    dist = stats.get("score_distribution", {})
    def m(k):
        return dist.get(k, {}).get("mean")
    return {
        "n_tasks": stats.get("n_tasks"),
        "qa_accuracy": m("qa_accuracy"),
        "accuracy": m("accuracy"),
        "verl_acc": m("verl_acc"),
        "composite_reward": m("composite_reward"),
        "action_score": m("action_score"),
    }


# ══════════════════════════════════════════════════════════════════════
#  The loop
# ══════════════════════════════════════════════════════════════════════


def run_loop(cfg: LoopConfig, hooks: Optional[Hooks] = None) -> dict:
    hooks = hooks or Hooks(dry_run=cfg.dry_run)
    root = Path(cfg.out_root)
    root.mkdir(parents=True, exist_ok=True)
    (root / "loop_config.json").write_text(
        json.dumps(asdict(cfg), indent=2, default=str), encoding="utf-8")

    curve: list[dict] = []
    curve_path = root / "star_curve.json"
    if cfg.resume and curve_path.exists():
        try:
            curve = json.loads(curve_path.read_text(encoding="utf-8")).get("iterations", [])
        except Exception:
            curve = []

    policy = cfg.base_model
    for it in range(cfg.iterations):
        it_dir = root / f"iter_{it:02d}"
        it_dir.mkdir(parents=True, exist_ok=True)
        state_path = it_dir / "state.json"

        if cfg.resume and state_path.exists():
            st = json.loads(state_path.read_text(encoding="utf-8"))
            if st.get("done"):
                logger.info(f"[star] iteration {it} already complete — resuming past it")
                policy = st["checkpoint"]
                if not any(r["iteration"] == it for r in curve):
                    curve.append(st.get("curve_row", {"iteration": it}))
                continue

        logger.info(f"[star] ===== iteration {it} — rolling out {policy} =====")
        srv, url = hooks.serve(cfg, policy, root / "logs" / f"sglang_iter{it:02d}.log")
        try:
            # Held-out probe of the CURRENT policy, before it is changed.  At
            # it=0 this is the base model's score, which anchors the curve.
            heldout = {}
            if cfg.heldout_size != 0:
                hcmd = generate_command(cfg, policy, url, it_dir / "heldout",
                                        split=cfg.heldout_split, samples=1,
                                        temperature=cfg.heldout_temperature,
                                        eval_only=True, limit=cfg.heldout_size)
                hstats = hooks.generate(hcmd, it_dir / "heldout")
                heldout = heldout_summary(hstats)

            gcmd = generate_command(cfg, policy, url, it_dir / "gen",
                                    split=cfg.split, samples=cfg.samples_per_task,
                                    temperature=cfg.temperature,
                                    eval_only=False, limit=cfg.limit)
            gen_stats = hooks.generate(gcmd, it_dir / "gen")
        finally:
            hooks.stop(srv)

        verdict = gen_stats.get("threshold_verdict")
        if verdict not in (None, "ok") and not cfg.allow_uninformative:
            # At iteration 0 a degenerate acceptance rate means the threshold or
            # the signal is wrong and nothing downstream is interpretable.
            # Later on, a HIGH rate is the expected STaR endgame (the policy has
            # learned to solve the pool) and is a result, not a bug — so it is
            # recorded and the loop continues.
            if it == 0 or verdict in ("empty", "uninformative_zero"):
                raise RuntimeError(
                    f"iteration {it}: acceptance rate is degenerate ({verdict}, "
                    f"{gen_stats.get('acceptance_rate')}). Re-choose --accept-on / "
                    "--accept-threshold, or pass --allow-uninformative to proceed anyway.")
            logger.warning(f"[star] iteration {it}: acceptance verdict={verdict} — recorded, continuing")

        # ── dataset for this iteration ──
        if cfg.sft_source == "trajectory_dir":
            data_path = it_dir / "gen" / "trajectory_dir"
            n_examples = gen_stats.get("n_selected") or 0
        else:
            sources = [root / f"iter_{j:02d}" / "gen" / "star_sft.jsonl"
                       for j in (range(it + 1) if cfg.dataset_scope == "accumulated" else [it])]
            data_path = it_dir / "sft_data.jsonl"
            if hooks.dry_run:
                n_examples = gen_stats.get("n_selected") or 0
            else:
                n_examples = concat_sft_files(sources, data_path)
                if n_examples == 0:
                    raise RuntimeError(
                        f"iteration {it}: no accepted trajectories to train on "
                        f"({[str(s) for s in sources]})")

        # ── SFT ──
        init_model = cfg.base_model if cfg.init_from == "base" else policy
        sft_out = it_dir / "sft"
        cfg_path = it_dir / "sft_config.yaml"
        _write_yaml(sft_config_dict(cfg, init_model, data_path, sft_out,
                                    f"star_iter{it:02d}"), cfg_path)
        checkpoint = hooks.sft(sft_command(cfg, cfg_path), sft_out)

        row = curve_row(it, policy, gen_stats, heldout, n_examples, init_model)
        curve = [r for r in curve if r.get("iteration") != it] + [row]
        curve.sort(key=lambda r: r["iteration"])
        # A dry run must never leave a "done" marker behind: the next REAL run
        # resumes past any iteration whose state.json says done, so writing one
        # here would silently skip training.
        if not hooks.dry_run:
            state_path.write_text(json.dumps(
                {"done": True, "checkpoint": checkpoint, "curve_row": row},
                indent=2, default=str), encoding="utf-8")
            _write_curve(curve_path, cfg, curve)
        policy = checkpoint

    # Final held-out probe of the trained policy, so the last iteration's SFT
    # is represented on the curve rather than only its input.
    final = {}
    if cfg.heldout_size != 0:
        srv, url = hooks.serve(cfg, policy, root / "logs" / "sglang_final.log")
        try:
            hcmd = generate_command(cfg, policy, url, root / "heldout_final",
                                    split=cfg.heldout_split, samples=1,
                                    temperature=cfg.heldout_temperature,
                                    eval_only=True, limit=cfg.heldout_size)
            final = heldout_summary(hooks.generate(hcmd, root / "heldout_final"))
        finally:
            hooks.stop(srv)
    curve.append({"iteration": cfg.iterations, "policy_rolled_out": policy,
                  "heldout": final, "final": True})
    if not hooks.dry_run:
        _write_curve(curve_path, cfg, curve)

    print_curve(curve)
    return {"final_policy": policy, "iterations": curve, "curve_path": str(curve_path)}


def _write_curve(path: Path, cfg: LoopConfig, curve: list[dict]) -> None:
    path.write_text(json.dumps(
        {"config": asdict(cfg), "iterations": curve}, indent=2, default=str),
        encoding="utf-8")


def _write_yaml(d: dict, path: Path) -> None:
    import yaml  # noqa: PLC0415
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(d, sort_keys=False), encoding="utf-8")


def print_curve(curve: list[dict]) -> None:
    print("=" * 96)
    print("  STaR iteration curve")
    print("=" * 96)
    print(f"  {'it':>3} {'accept':>8} {'cover':>8} {'n_train':>9} "
          f"{'ho_qa_acc':>10} {'ho_verl_acc':>12} {'ho_composite':>13}")
    print("-" * 96)
    for r in curve:
        ho = r.get("heldout") or {}
        def f(v, w=10, p=3):
            return f"{v:>{w}.{p}f}" if isinstance(v, (int, float)) else f"{'-':>{w}}"
        print(f"  {r.get('iteration'):>3} {f(r.get('acceptance_rate'), 8)} "
              f"{f(r.get('task_coverage'), 8)} "
              f"{(str(r.get('n_train_examples')) if r.get('n_train_examples') is not None else '-'):>9} "
              f"{f(ho.get('qa_accuracy'), 10)} {f(ho.get('verl_acc'), 12)} "
              f"{f(ho.get('composite_reward'), 13)}")
    print("=" * 96)


# ══════════════════════════════════════════════════════════════════════
#  CLI
# ══════════════════════════════════════════════════════════════════════


def preflight(cfg: LoopConfig) -> list[str]:
    """Everything that must exist before a real run.  Returns problems."""
    problems = []
    if not cfg.dry_run:
        if not Path(cfg.base_model, "config.json").exists():
            problems.append(f"no config.json under base model {cfg.base_model}")
        try:
            import trl  # noqa: F401,PLC0415
        except Exception:
            problems.append(
                "trl is not importable in this environment — "
                "bioagents/training/sft_trainer.py imports it inside train(). "
                "Install it into the run venv before launching the SFT half "
                "(the generation half does not need it).")
    base = HCGYM_ROOT / "data" / "domains" / cfg.pool
    for f in ("tasks.json", "split_tasks.json"):
        if not (base / f).exists():
            problems.append(f"missing pool file {base / f}")
    if not STAR_GENERATE.exists():
        problems.append(f"missing {STAR_GENERATE}")
    if not SFT_TRAINER.exists():
        problems.append(f"missing {SFT_TRAINER}")
    if cfg.init_from not in ("base", "previous"):
        problems.append(f"--init-from must be base|previous, got {cfg.init_from}")
    if cfg.dataset_scope not in ("current", "accumulated"):
        problems.append(f"--dataset-scope must be current|accumulated, got {cfg.dataset_scope}")
    return problems


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="STaR outer loop (reimplementation)")
    p.add_argument("--base-model", required=True)
    p.add_argument("--out-root", required=True)
    p.add_argument("--iterations", type=int, default=3)
    p.add_argument("--pool", default="full_4modality_clean")
    p.add_argument("--split", default="train")
    p.add_argument("--limit", type=int, default=0)
    p.add_argument("--samples-per-task", type=int, default=3)
    p.add_argument("--temperature", type=float, default=1.0)
    p.add_argument("--max-turns", type=int, default=5)
    p.add_argument("--max-new-tokens", type=int, default=2048)
    p.add_argument("--workers", type=int, default=8)
    p.add_argument("--think", dest="no_think", action="store_false",
                   help="leave the think() tool in (the eval harness runs --no-think)")
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--accept-on", default="qa_accuracy")
    p.add_argument("--accept-threshold", type=float, default=None)
    p.add_argument("--max-accepted-per-task", type=int, default=1)
    p.add_argument("--allow-uninformative", action="store_true")
    p.add_argument("--init-from", default="base", choices=["base", "previous"])
    p.add_argument("--dataset-scope", default="current", choices=["current", "accumulated"])
    p.add_argument("--sft-source", default="sft_path", choices=["sft_path", "trajectory_dir"])
    p.add_argument("--sft-gpus", type=int, default=7)
    p.add_argument("--sft-epochs", type=int, default=2)
    p.add_argument("--sft-lr", type=float, default=1e-5)
    p.add_argument("--sft-batch", type=int, default=1)
    p.add_argument("--sft-grad-accum", type=int, default=8)
    p.add_argument("--sft-max-length", type=int, default=8192)
    p.add_argument("--peft", action="store_true",
                   help="LoRA instead of full fine-tuning (NOT comparable to the RL arms)")
    p.add_argument("--serve-port", type=int, default=31500)
    p.add_argument("--serve-gpus", type=int, default=8)
    p.add_argument("--server-url", default=None,
                   help="use an already-running server instead of serving per iteration")
    p.add_argument("--heldout-split", default="test")
    p.add_argument("--heldout-size", type=int, default=200)
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--no-resume", dest="resume", action="store_false")
    return p


def cfg_from_args(a) -> LoopConfig:
    return LoopConfig(
        base_model=a.base_model, out_root=a.out_root, iterations=a.iterations,
        pool=a.pool, split=a.split, limit=a.limit,
        samples_per_task=a.samples_per_task, temperature=a.temperature,
        max_turns=a.max_turns, max_new_tokens=a.max_new_tokens, workers=a.workers,
        no_think=a.no_think, seed=a.seed,
        accept_on=a.accept_on, accept_threshold=a.accept_threshold,
        max_accepted_per_task=a.max_accepted_per_task,
        allow_uninformative=a.allow_uninformative,
        init_from=a.init_from, dataset_scope=a.dataset_scope, sft_source=a.sft_source,
        sft_gpus=a.sft_gpus, sft_epochs=a.sft_epochs, sft_lr=a.sft_lr,
        sft_batch=a.sft_batch, sft_grad_accum=a.sft_grad_accum,
        sft_max_length=a.sft_max_length, peft=a.peft,
        serve_port=a.serve_port, serve_gpus=a.serve_gpus, server_url=a.server_url,
        heldout_split=a.heldout_split, heldout_size=a.heldout_size,
        dry_run=a.dry_run, resume=a.resume,
    )


def main(argv=None) -> int:
    cfg = cfg_from_args(build_parser().parse_args(argv))
    problems = preflight(cfg)
    for p in problems:
        print(f"[preflight] {p}")
    if problems and not cfg.dry_run:
        return 2
    if cfg.dry_run:
        print(f"DRYRUN base_model={cfg.base_model}")
        print(f"DRYRUN out_root={cfg.out_root}")
        print(f"DRYRUN iterations={cfg.iterations} samples_per_task={cfg.samples_per_task} "
              f"max_turns={cfg.max_turns}")
        print(f"DRYRUN accept_on={cfg.accept_on} threshold="
              f"{cfg.accept_threshold if cfg.accept_threshold is not None else 'default'}")
        print(f"DRYRUN init_from={cfg.init_from} dataset_scope={cfg.dataset_scope} "
              f"sft_source={cfg.sft_source} peft={cfg.peft}")
        print(f"DRYRUN preflight_problems={len(problems)}")
    run_loop(cfg)
    if cfg.dry_run:
        print("DRYRUN ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
